name: 'Lint Test 00'
description: 'Lint test!'
inputs:
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
  workspace:
    description: 'The GitHub worskpace'
    default: ${{ github.workspace }}
  repository:
    description: 'The full name of the target repository.'
    default: ${{ github.repository }}
runs:
  using: 'node12'
  main: 'index.js'
